// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

syntax = "proto3";

package google.cloud.speech.v2;

option cc_enable_arenas = true;
option csharp_namespace = "Google.Cloud.Speech.V2";
option go_package = "google.golang.org/genproto/googleapis/cloud/speech/v2;speech";
option java_multiple_files = true;
option java_outer_classname = "CloudSpeechProto";
option java_package = "com.google.cloud.speech.v2";
option php_namespace = "Google\\Cloud\\Speech\\V2";

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

// Service that implements Google Cloud Speech API.
service Speech {
  // Performs bidirectional streaming speech recognition: receive results while
  // sending audio.
  rpc StreamingRecognize(stream StreamingRecognizeRequest)
      returns (stream StreamingRecognizeResponse);
}

// The top-level message sent by the client for the `StreamingRecognize`
// method. Multiple `StreamingRecognizeRequest` messages are sent. The first
// message must contain a `recognizer` that specifies the recognition
// configuration. Subsequent messages must contain `audio` to send the audio
// data.
message StreamingRecognizeRequest {
  oneof streaming_request {
    // Required. The name of the Recognizer to use during recognition. The
    // expected format is
    // `projects/{project}/locations/{location}/recognizers/{recognizer}`.
    // The {recognizer} segment may be set to `_` to use an empty implicit
    // Recognizer.
    string recognizer = 4;

    // StreamingRecognitionConfig to be used for this recognition attempt.
    // If provided, it will override the default RecognitionConfig stored in
    // the Recognizer.
    StreamingRecognitionConfig streaming_config = 6;

    // The audio data bytes encoded as specified in RecognitionConfig.
    // As with all bytes fields, proto buffers use a pure binary representation,
    // whereas JSON representations use base64.
    bytes audio = 5;
  }
}

// `StreamingRecognitionConfig` provides information to the recognizer
// that specifies how to process the request.
message StreamingRecognitionConfig {
  // Required. Features and audio metadata to use for the Automatic Speech
  // Recognition. This field in combination with the
  // [config_mask][google.cloud.speech.v2.StreamingRecognitionConfig.config_mask]
  // field can be used to override or set default values in the
  // [Recognizer][google.cloud.speech.v2.Recognizer] stored in the service.
  RecognitionConfig config = 1;

  // The default behavior for speech recognition is to return a single result.
  // Set this field to `true` to get interim results (tentative hypotheses) as
  // they become available. Interim results are not guaranteed to be stable.
  bool enable_voice_activity_events = 5;
}

// Provides information to the [Recognizer][google.cloud.speech.v2.Recognizer]
// that specifies how to process the recognition request.
message RecognitionConfig {
  // The decoding strategy that should be applied to the audio content.
  oneof decoding_config {
    // Automatically detect decoding of the audio. Does not perform
    // automatic sample rate detection.  Requires that digital audio be
    // provided in a supported format.
    AutoDetectDecodingConfig auto_decoding_config = 7;

    // Explicitly specified decoding parameters.  Required if using
    // headerless audio (e.g., raw audio bytes).
    ExplicitDecodingConfig explicit_decoding_config = 8;
  }

  // Required. The language of the supplied audio as a
  // [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) language tag.
  // Example: "en-US".
  // See [Language
  // Support](https://cloud.google.com/speech-to-text/docs/languages) for a
  // list of the currently supported language codes.
  repeated string language_codes = 1;

  // The speech model to use for recognition. If not specified, the service
  // will select a default model to use.
  // Select the model best suited to your domain to get best results.
  string model = 9;

  // Speech recognition features to enable.
  RecognitionFeatures features = 2;

  // Speech adaptation context that weights how the speech recognition
  // model interprets the supplied audio, and/or influences the
  // "transcription_normalization" behavior.
  SpeechAdaptation adaptation = 6;
}

// Automatically detected decoding parameters.
message AutoDetectDecodingConfig {
}

// Explicitly specified decoding parameters.
message ExplicitDecodingConfig {
  // The encoding of the audio data sent in the request.
  //
  // All encodings support only 1 channel (mono) audio, unless the
  // `audio_channel_count` field in `RecognitionConfig` is set to a different
  // value.
  //
  // For best results, the audio source should be captured and transmitted using
  // a lossless encoding (`FLAC` or `LINEAR16`). The accuracy of the speech
  // recognition can be reduced if lossy codecs are used to capture or transmit
  // audio, particularly if background noise is present. Lossy codecs include
  // `MULAW`, `AMR`, `AMR_WB`, `OGG_OPUS`, `SPEEX_WITH_HEADER_BYTE`, and `MP3`.
  enum AudioEncoding {
    // Not specified.
    AUDIO_ENCODING_UNSPECIFIED = 0;

    // Uncompressed 16-bit signed little-endian samples (Linear PCM).
    LINEAR16 = 1;

    // `FLAC` (Free Lossless Audio
    // Codec) is the recommended encoding because it is lossless (therefore
    // recognition is not compromised) and requires only about half the
    // bandwidth of `LINEAR16`. `FLAC` stream encoding supports 16-bit and
    // 24-bit samples, however, not all fields in `STREAMINFO` are supported.
    FLAC = 2;

    // 8-bit samples that compand 14-bit audio samples using G.711 PCMU/mu-law.
    MULAW = 3;

    // Adaptive Multi-Rate Narrowband codec. `sample_rate_hertz` must be 8000.
    AMR = 4;

    // Adaptive Multi-Rate Wideband codec. `sample_rate_hertz` must be 16000.
    AMR_WB = 5;

    // Opus encoded audio frames in Ogg container
    // ([OggOpus](https://wiki.xiph.org/OggOpus)).
    // `sample_rate_hertz` must be 16000.
    OGG_OPUS = 6;

    // Although the use of lossy encodings is not recommended, if a very low
    // bitrate encoding is required, `OGG_OPUS` is highly preferred over
    // Speex encoding. The [Speex](https://speex.org/) encoding supported by
    // Cloud Speech API has a header byte in each block, as in MIME type
    // `audio/x-speex-with-header-byte`.
    // It is a variant of the RTP Speex encoding defined in
    // [RFC 5574](https://tools.ietf.org/html/rfc5574).
    // The stream is a sequence of blocks, one block per RTP packet. Each
    // block starts with a byte containing the length of the block, in bytes,
    // followed by one or more frames of Speex data, padded to an integral
    // number of bytes (octets) as specified in RFC 5574. In other words, each
    // RTP header is replaced with a single byte containing the block length.
    // Only Speex wideband is supported. `sample_rate_hertz` must be 16000.
    SPEEX_WITH_HEADER_BYTE = 7;

    // MP3 audio. MP3 encoding is a Beta feature and only available in
    // v1p1beta1. Support all standard MP3 bitrates (which range from 32-320
    // kbps). When using this encoding, `sample_rate_hertz` has to match the
    // sample rate of the file being used.
    MP3 = 8;

    // Opus encoded audio frames in WebM container
    // ([OggOpus](https://wiki.xiph.org/OggOpus)).  `sample_rate_hertz` must be
    // 16000.
    WEBM_OPUS = 9;
  }

  // Required. The encoding of the audio data sent in the request.
  AudioEncoding encoding = 1;

  // Required. Sample rate in Hertz of the audio data sent in the request.
  // Valid values are: 8000-48000. 16000 is optimal. For best results, set the
  // sampling rate of the audio source to 16000 Hz. If that's not possible, use
  // the native sample rate of the audio source (instead of re-sampling).
  int32 sample_rate_hertz = 2;

  // Required. The number of channels in the input audio data.
  // ONLY set this for MULTI-CHANNEL recognition.
  // Valid values for LINEAR16, FLAC, and WAV are `1`-`8`.
  // Valid value for OGG_OPUS is `1`-`254`.
  // Valid value for MULAW, AMR, AMR_WB and SPEEX_WITH_HEADER_BYTE is only `1`.
  // If `0` or omitted, defaults to one channel (mono).
  // Note: We only recognize the first channel by default.
  // To perform independent recognition on each channel set
  // `enable_separate_recognition_per_channel` to 'true'.
  int32 audio_channel_count = 3;
}

// Available recognition features.
message RecognitionFeatures {
  // Multi-channel Audio modes.
  enum MultiChannelMode {
    // Default value for the multi-channel mode. If the audio contains
    // multiple channels, only the first channel will be transcribed; other
    // channels will be ignored.
    MULTI_CHANNEL_MODE_UNSPECIFIED = 0;

    // If selected, each channel in the provided audio is transcribed
    // independently. This cannot be selected if the selected
    // [model][google.cloud.speech.v2.RecognitionConfig.model] is `latest_short`.
    SEPARATE_RECOGNITION_PER_CHANNEL = 1;
  }

  // If set to `true`, the server will attempt to filter out profanities,
  // replacing all but the initial character in each filtered word with
  // asterisks, for instance, "f***". If set to `false` or omitted, profanities
  // won't be filtered out.
  bool profanity_filter = 1;

  // If `true`, the top result includes a list of words and the confidence for
  // those words. If `false`, no word-level confidence information is returned.
  // The default is `false`.
  bool enable_word_confidence = 2;

  // If `true`, the top result includes a list of words and the start and end
  // time offsets (timestamps) for those words. If `false`, no word-level time
  // offset information is returned. The default is `false`.
  bool enable_word_time_offsets = 3;

  // If `true`, add punctuation to recognition result hypotheses. This feature
  // is only available in select languages. The default `false` value does not
  // add punctuation to result hypotheses.
  bool enable_automatic_punctuation = 4;

  // The spoken punctuation behavior for the call. If `true`, replaces spoken
  // punctuation with the corresponding symbols in the request. For example,
  // "how are you question mark" becomes "how are you?". The default value is
  // `false`.
  bool enable_spoken_punctuation = 5;

  // The spoken emoji behavior for the call. If `true`, adds spoken emoji
  // formatting for the request. This will replace spoken emojis with the
  // corresponding Unicode symbols in the final transcript. If `false`, spoken
  // emojis are not replaced.
  bool enable_spoken_emojis = 6;

  // Mode for recognizing multi-channel audio.
  MultiChannelMode multi_channel_mode = 7;

  // Configuration to enable speaker diarization.
  SpeakerDiarizationConfig diarization_config = 8;
}

// Configuration to enable speaker diarization.
message SpeakerDiarizationConfig {
  // Required. Minimum number of speakers in the conversation. This range gives
  // you more flexibility by allowing the system to automatically determine the
  // correct number of speakers. If not set, the default value is 2.
  // Supported values: 1-6.
  int32 min_speaker_count = 2;

  // Required. Maximum number of speakers in the conversation. This range gives
  // you more flexibility by allowing the system to automatically determine the
  // correct number of speakers. If not set, the default value is 6.
  // Valid values are: 1-6.
  int32 max_speaker_count = 3;
}

// Speech adaptation context.
message SpeechAdaptation {
  // A collection of phrase sets. To specify the hints inline, leave the
  // phrase set's `name` blank and fill in the rest of its fields. Otherwise,
  // you can specify the phrase set's name to reference a set defined in the
  // parent resource.
  repeated PhraseSet phrase_sets = 1;

  // A collection of phrase set resource names to use.
  repeated string phrase_set_references = 2;
}

// PhraseSet for biasing in speech recognition. A PhraseSet is used to provide
// "hints" to the speech recognizer to favor specific words and phrases in the
// results.
message PhraseSet {
  message Phrase {
    // The phrase itself.
    string value = 1;

    // Hint Boost. Positive value will increase the probability that a specific
    // phrase will be recognized over other similar sounding phrases. The
    // higher the boost, the higher the chance of false positive recognition as
    // well. Negative boost values would correspond to anti-biasing. Anti-biasing
    // is not enabled, so negative boost will simply be ignored. Though
    // `boost` can accept a wide range of positive values, most use cases are
    // best served with values between 0 and 20. We recommend using a binary
    // search approach to finding the optimal value for your use case. Boost
    // will be ignored if the phrase is longer than 100 UTF-8 characters.
    float boost = 2;
  }

  // The resource name of the phrase set.
  string name = 1;

  // A list of word and phrases.
  repeated Phrase phrases = 2;

  // Hint Boost. Overrides the boost set at the phrase level. Positive value
  // will increase the probability that a specific phrase will be recognized
  // over other similar sounding phrases. The higher the boost, the higher the
  // chance of false positive recognition as well. Negative boost values would
  // correspond to anti-biasing. Anti-biasing is not enabled, so negative
  // boost will simply be ignored. Though `boost` can accept a wide range of
  // positive values, most use cases are best served with values between 0 (
  // default) and 20. We recommend using a binary search approach to finding
  // the optimal value for your use case. Speech recognition will skip
  // PhraseSets with a boost value of 0.
  float boost = 4;
}

// `StreamingRecognizeResponse` is the only message returned to the client by
// `StreamingRecognize`. A series of zero or more `StreamingRecognizeResponse`
// messages are streamed back to the client. If there is no recognizable
// audio, and `single_utterance` is set to false, then no messages are
// streamed back to the client.
//
// Here's an example of a series of `StreamingRecognizeResponse`s that might be
// returned while processing audio:
//
// 1. results { alternatives { transcript: "tube" } stability: 0.01 }
//
// 2. results { alternatives { transcript: "to be a" } stability: 0.01 }
//
// 3. results { alternatives { transcript: "to be" } stability: 0.9 }
//    results { alternatives { transcript: " or not to be" } stability: 0.01 }
//
// 4. results { alternatives { transcript: "to be or not to be"
//             confidence: 0.92 }
//            alternatives { transcript: "to bee or not to bee" }
//            is_final: true }
//
// 5. results { alternatives { transcript: " that's" } stability: 0.01 }
//
// 6. results { alternatives { transcript: " that is" } stability: 0.9 }
//    results { alternatives { transcript: " the question" } stability: 0.01 }
//
// 7. results { alternatives { transcript: " that is the question"
//             confidence: 0.98 }
//            alternatives { transcript: " that was the question" }
//            is_final: true }
//
// Notes:
//
// - Only two of the above responses #4 and #7 contain final results; they are
//   indicated by `is_final: true`. The others are interim results. Each
//   interim result updates the transcript instead of appending to it.
//
// - The above example has `single_utterance: false`. If you had set
//   `single_utterance: true`, then responses #4 and #7 would not occur, since
//   you would have already received the final result from #4.
message StreamingRecognizeResponse {
  // A streaming speech recognition result corresponding to a portion of the
  // audio that is currently being processed.
  message StreamingRecognitionResult {
    // May contain one or more recognition hypotheses (up to the
    // maximum specified in `max_alternatives`).
    // These alternatives are ordered in terms of accuracy, with the top (first)
    // alternative being the most probable, as ranked by the recognizer.
    repeated SpeechRecognitionAlternative alternatives = 1;

    // If `false`, this `StreamingRecognitionResult` represents an
    // interim result that may change. If `true`, this is the final time the
    // speech service will return this particular
    // `StreamingRecognitionResult`, the recognizer will not return any
    // further hypotheses for this portion of the transcript and corresponding
    // audio.
    bool is_final = 2;

    // An estimate of the likelihood that the recognizer will not
    // change its guess about this interim result. Values range from 0.0
    // (completely unstable) to 1.0 (completely stable).
    // This field is only provided for interim results (`is_final=false`).
    // The default of 0.0 is a sentinel value indicating `stability` was not set.
    float stability = 3;

    // Time offset of the end of this result relative to the
    // beginning of the audio.
    google.protobuf.Duration result_end_offset = 4;

    // For multi-channel audio, this is the channel number corresponding to the
    // recognized result for the audio from that channel.
    // For `audio_channel_count = N`, its output values can range from `1` to
    // `N`. The channel tag is provided only when the recognizer receives audio
    // from multiple channels, e.g. `audio_channel_count > 1`.
    int32 channel_tag = 5;

    // The [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) language tag
    // of the language in this result. This language code was detected to have
    // the most likelihood of being spoken in the audio.
    string language_code = 6;
  }

  // This repeated list contains zero or more results that
  // correspond to consecutive portions of the audio currently being processed.
  // It contains zero or one `is_final=true` result (the newly settled portion),
  // followed by zero or more `is_final=false` results (the interim results).
  repeated StreamingRecognitionResult results = 5;

  // Indicates the type of speech event.
  SpeechEventType speech_event_type = 3;

  // Time offset between the beginning of the audio and event emission.
  google.protobuf.Duration speech_event_offset = 7;
}

// Alternative hypotheses (a.k.a. n-best list).
message SpeechRecognitionAlternative {
  // Transcript text representing the words that the user spoke.
  string transcript = 1;

  // The confidence estimate between 0.0 and 1.0. A higher number
  // indicates an estimated greater likelihood that the recognized words are
  // correct. This field is set only for the top alternative of a non-streaming
  // result or, of a streaming result where `is_final=true`.
  // This field is not guaranteed to be accurate and users should not rely on it
  // to be always provided.
  // The default of 0.0 is a sentinel value indicating `confidence` was not set.
  float confidence = 2;

  // A list of word-specific information for each recognized word.
  // Note: When `enable_speaker_diarization` is true, you will see all the words
  // from the beginning of the audio.
  repeated WordInfo words = 3;
}

// Word-specific information for recognized words.
message WordInfo {
  // Time offset relative to the beginning of the audio,
  // and corresponding to the start of the spoken word.
  // This field is only set if `enable_word_time_offsets=true` and only
  // in the top hypothesis.
  // This is an experimental feature and the accuracy of the time offset can
  // vary.
  google.protobuf.Duration start_offset = 1;

  // Time offset relative to the beginning of the audio,
  // and corresponding to the end of the spoken word.
  // This field is only set if `enable_word_time_offsets=true` and only
  // in the top hypothesis.
  // This is an experimental feature and the accuracy of the time offset can
  // vary.
  google.protobuf.Duration end_offset = 2;

  // The word corresponding to this set of information.
  string word = 3;

  // The confidence estimate between 0.0 and 1.0. A higher number
  // indicates an estimated greater likelihood that the recognized words are
  // correct. This field is set only for the top alternative of a non-streaming
  // result or, of a streaming result where `is_final=true`.
  // This field is not guaranteed to be accurate and users should not rely on it
  // to be always provided.
  // The default of 0.0 is a sentinel value indicating `confidence` was not set.
  float confidence = 4;

  // A distinct integer value is assigned for every speaker within
  // the audio. This field specifies which one of those speakers was detected to
  // have spoken this word. Value ranges from '1' to diarization_speaker_count.
  // speaker_tag is set if enable_speaker_diarization = 'true' and only for the
  // top alternative.
  int32 speaker_tag = 5;
}

// Indicates the type of speech event.
enum SpeechEventType {
  // No speech event specified.
  SPEECH_EVENT_UNSPECIFIED = 0;

  // This event indicates that the server has detected the end of the user's
  // speech utterance and expects no additional speech. Therefore, the server
  // will not process additional audio (although it may subsequently return
  // additional results). The client should stop sending additional audio
  // data, half-close the gRPC connection, and wait for any additional results
  // until the server closes the gRPC connection. This event is only sent if
  // `single_utterance` was set to `true`, and is not used otherwise.
  END_OF_SINGLE_UTTERANCE = 1;

  // This event indicates that the server has detected the beginning of human
  // voice activity in the stream. This event can be returned multiple times
  // during a stream. This event is only sent if `voice_activity_events` is
  // set to true.
  SPEECH_ACTIVITY_BEGIN = 2;

  // This event indicates that the server has detected the end of human voice
  // activity in the stream. This event can be returned multiple times
  // during a stream. This event is only sent if `voice_activity_events` is set
  // to true.
  SPEECH_ACTIVITY_END = 3;
}