// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: speech.proto

#include "speech.pb.h"
#include "speech.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace google {
namespace cloud {
namespace speech {
namespace v2 {

static const char* Speech_method_names[] = {
  "/google.cloud.speech.v2.Speech/StreamingRecognize",
};

std::unique_ptr< Speech::Stub> Speech::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Speech::Stub> stub(new Speech::Stub(channel, options));
  return stub;
}

Speech::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamingRecognize_(Speech_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::google::cloud::speech::v2::StreamingRecognizeRequest, ::google::cloud::speech::v2::StreamingRecognizeResponse>* Speech::Stub::StreamingRecognizeRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::google::cloud::speech::v2::StreamingRecognizeRequest, ::google::cloud::speech::v2::StreamingRecognizeResponse>::Create(channel_.get(), rpcmethod_StreamingRecognize_, context);
}

void Speech::Stub::async::StreamingRecognize(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::google::cloud::speech::v2::StreamingRecognizeRequest,::google::cloud::speech::v2::StreamingRecognizeResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::google::cloud::speech::v2::StreamingRecognizeRequest,::google::cloud::speech::v2::StreamingRecognizeResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamingRecognize_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::google::cloud::speech::v2::StreamingRecognizeRequest, ::google::cloud::speech::v2::StreamingRecognizeResponse>* Speech::Stub::AsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::google::cloud::speech::v2::StreamingRecognizeRequest, ::google::cloud::speech::v2::StreamingRecognizeResponse>::Create(channel_.get(), cq, rpcmethod_StreamingRecognize_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::google::cloud::speech::v2::StreamingRecognizeRequest, ::google::cloud::speech::v2::StreamingRecognizeResponse>* Speech::Stub::PrepareAsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::google::cloud::speech::v2::StreamingRecognizeRequest, ::google::cloud::speech::v2::StreamingRecognizeResponse>::Create(channel_.get(), cq, rpcmethod_StreamingRecognize_, context, false, nullptr);
}

Speech::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Speech_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Speech::Service, ::google::cloud::speech::v2::StreamingRecognizeRequest, ::google::cloud::speech::v2::StreamingRecognizeResponse>(
          [](Speech::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::google::cloud::speech::v2::StreamingRecognizeResponse,
             ::google::cloud::speech::v2::StreamingRecognizeRequest>* stream) {
               return service->StreamingRecognize(ctx, stream);
             }, this)));
}

Speech::Service::~Service() {
}

::grpc::Status Speech::Service::StreamingRecognize(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::google::cloud::speech::v2::StreamingRecognizeResponse, ::google::cloud::speech::v2::StreamingRecognizeRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace google
}  // namespace cloud
}  // namespace speech
}  // namespace v2

